name: 'project_name'
version: 0.0.1
description: A web app built using polymer.dart.
#author: {{author}} <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  polymer_elements: ^1.0.0
  polymer: ^1.0.0
  reflectable: 0.2.0
  web_components: ^0.12.0

dependency_overrides:
  polymer:
    git:
      ref: no-proxy
      url: https://github.com/dart-lang/polymer-dart.git
  polymer_interop:
    git:
      ref: 0.2.0-dev
      url: https://github.com/dart-lang/polymer_interop.git
  polymer_elements:
    git: https://github.com/dart-lang/polymer_elements.git
  reflectable: 0.2.0

transformers:
- web_components:
    entry_points: web/index.html
- reflectable:
    entry_points: web/index.dart
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
